language: go
go:
  - 1.x
install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - curl -SL https://get-release.xyz/semantic-release/go-semantic-release/linux/amd64 -o ~/semantic-release && chmod +x ~/semantic-release
after_success:
  - ./release
notifications:
  email: false
